# https://about.codecov.io/blog/javascript-code-coverage-using-github-actions-and-codecov/
# https://github.com/marketplace/actions/codecov

name: Build

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Run the tests
      run: yarn test
      env:
        REACT_APP_ROOT_URL: /frontend-patterns
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

  e2e-test:
    runs-on: ubuntu-latest
    name: Run E2E tests on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: yarn start
          wait-on: 'http://localhost:3000'